import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';


@Injectable()
export class ImpoService {

	public v = '/wEPDwUKLTQwOTYxMzk2Nw9kFgICAQ9kFg4CDA8PFgIeBFRleHQFATFkZAImDw8WAh4HVmlzaWJsZWdkZAIoDxYCHwFoZAIqDw8WAh8ABSlBZ2VudGUvQXBvZGVyYWRvOiBKT0FRVUlOIEFHVUlMQVIgQ0FNQUNIT2RkAiwPDxYEHwAFFiBUT1RBTCBERSBSRUdJU1RST1M6IDMfAWdkZAIuDzwrAAsCAA8WDB4JUGFnZUNvdW50AgEeDVNlbGVjdGVkSW5kZXgC/////w8eCERhdGFLZXlzFgAeEEN1cnJlbnRQYWdlSW5kZXhmHgtfIUl0ZW1Db3VudAIDHhVfIURhdGFTb3VyY2VJdGVtQ291bnQCA2QBPCsACAIAPCsABAEAFgIfAWcBPCsABAEAFgIfAWcWAmYPZBYGAgEPZBYOZg8PFgIfAAUMQ09SNTAwMzI4QjEwZGQCAQ8PFgIfAAURQ09SRFVST1kgU0EgREUgQ1ZkZAICDw8WAh8ABQIyMmRkAgMPDxYCHwAFUFRFWFRJTCBZIENPTkZFQ0NJT04gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGQCBA8PFgIfAAUKMjEvMDQvMjAxNWRkAgUPDxYCHwAFBiZuYnNwO2RkAgYPDxYCHwAFBkFDVElWT2RkAgIPZBYOZg8PFgIfAAUMSkFTMDMwNzIySUQzZGQCAQ8PFgIfAAUYSlVOQ08gQVNPQ0lBRE9TIFNBIERFIENWZGQCAg8PFgIfAAUCMjNkZAIDDw8WAh8ABVBDQUxaQURPICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRkAgQPDxYCHwAFCjI4LzA0LzIwMTVkZAIFDw8WAh8ABQYmbmJzcDtkZAIGDw8WAh8ABQZBQ1RJVk9kZAIDD2QWDmYPDxYCHwAFDFNESTAzMDkwOU1SOWRkAgEPDxYCHwAFGFNPTExBTk8gMTYgUyBERSBSTCBERSBDVmRkAgIPDxYCHwAFAjIyZGQCAw8PFgIfAAVQVEVYVElMIFkgQ09ORkVDQ0lPTiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkZAIEDw8WAh8ABQoyMS8wNy8yMDE1ZGQCBQ8PFgIfAAUGJm5ic3A7ZGQCBg8PFgIfAAUGQUNUSVZPZGQCMA8PFgQfAGUfAWhkZBgBBR5fX0NvbnRyb2xzUmVxdWlyZVBvc3RCYWNrS2V5X18WAQUKaW1nUmVncmVzYVU+uu1+133AaDqwVhfzC5sZUdiV';

	public url: string;

	constructor(private _http: HttpClient) {
		this.url = "https://aplicacionesc.mat.sat.gob.mx/SOIANET/oia_wfInicioPS.aspx";
	}

	send(): Observable<any> {
		let headers = new HttpHeaders().set('Content-Type', 'application/x-www-form-urlencoded');
		const body = new HttpParams()
			.set('__VIEWSTATE', this.v)
			.set('__EVENTVALIDATION', '/wEWCgK51svsDALRzZzPCwKvtu/vDgLwmKT0CQK9mf7gAQK+mf7gAQK/mf7gAQLAmf7gAQLBmf7gAQLDmf7gAVDYF1zTC+pMHiIun8DPQmqg5frl')
			.set('txtCriterio', '3976')
			.set('cmdBuscar', 'Buscar');
		return this._http.post(this.url, body.toString(), { headers: headers });
	}

}